[package]
name = "log-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
agent = { path = "../../agent" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

